### ISSUE TITLE
Registration script problem

### ISSUE THREAD

**Issue by ikb42** [anvilresearch/connect-example-angularjs#4]
Running `register_with_anvil_connect.sh` in my connect directory gives me this:

```
Registring nv add client {
  "client_name": "Angular example with popup for http://localhost:9000",
  "default_max_age": 36000,
  "redirect_uris": [
    "http://localhost:9000/callback_popup.html",
    "http://localhost:9000/rp.html"],
  "post_logout_redirect_uris": ["http://localhost:9000"],
  "trusted": "true"
}
Succeeded.
Define CLIENT_ID as follows in authconf.json:
{
...
  "CLIENT_ID" : "",
...
}
```

**Comment by christiansmith** [comment]
@oren @henrjk can you guys help out with this? Since accepting your PRs a while back, I don't recall how the configuration for this example works. 

@vsimonian I think we need to carve out some time on this README and bring it up to date with the latest CLI commands, etc.

**Comment by henrjk** [comment]
What is the status on the CLI? Should the script above switch to a new command.

The problem was caused by some validation not working anymore. I have worked around this by adding the following into the `register_with_anvil_connect.sh` script:

``` bash
client='{
  "client_name": "Angular example with <%= AUTH_DISPLAY %> for <%= APP_SERVER %>",
  "default_max_age": 36000,
  "redirect_uris": [
    "<%= APP_SERVER %>/<%= APP_AUTH_CALLBACK %>",
    "<%= APP_SERVER %>/rp.html"],
  "post_logout_redirect_uris": ["<%= APP_SERVER %>"],
  "trusted": true,
  "response_types": [
    "id_token token"
  ],
  "grant_types": [
    "implicit"
  ]
}'
```

Note the additions of response_types and grant_types. Previously the script worked with the assumed default values, when the definitions of response_types and grant_types were missing in the client JSON.

Is this a regression that should be fixed somewhere in core or are these value now required?

**Comment by ikb42** [comment]
In my case the problem was with `"trusted": "true"`, true here must be a boolean.
